### ISSUE TITLE
The domain heyjksn.github.io is moving to something else soon.

### ISSUE THREAD

**Issue by HeyJKSN** [HeyJKSN/heyjksn.github.io#8]
Hello everyone!
Ever since launch, the HeyJKSN website has gone under `heyjksn.github.io` and it's about time I change that.

From next week onwards, I'll be in talks with somebody on Discord in regards of getting a DNS provider to acknowledge the new domain.

If it goes to plan, the domain change will happen
If it doesn't, the domain will stay the same.

See you soon.
Jackson/HeyJKSN

**Comment by HeyJKSN** [comment]
🛃 The site domain has successfully transferred and the certificate was approved.

❗ The site has a false positive to it being **unsecure**, the site is secured with Cloudflare, Google Search Console and GitHub Pages. This is being fixed at the moment with @tyler-Github fixing the certificate.

🕔 This may take some time, *so please be pacient.*

**Comment by tyler-Github** [comment]
> 🛃 The site domain has successfully transferred and the certificate was approved.
> 
> ❗ The site has a false positive to it being **unsecure**, the site is secured with Cloudflare, Google Search Console and GitHub Pages. This is being fixed at the moment with @tyler-Github fixing the certificate.
> 
> 🕔 This may take some time, _so please be pacient._

Hello! I have now fixed the issue and added a few things.

**Comment by HeyJKSN** [comment]
> > 🛃 The site domain has successfully transferred and the certificate was approved.
> > ❗ The site has a false positive to it being **unsecure**, the site is secured with Cloudflare, Google Search Console and GitHub Pages. This is being fixed at the moment with @tyler-Github fixing the certificate.
> > 🕔 This may take some time, _so please be pacient._
> 
> Hello! I have now fixed the issue and added a few things.

It seems the website isn't sending any requests to the homepage.
![image](https://user-images.githubusercontent.com/98255028/152467635-5799be41-7a79-4179-ae8a-7410aa8f8e46.png)

**Comment by HeyJKSN** [comment]
Ignore the problem above, I forgot the www.

The website domain has successfully transferred
